### ISSUE TITLE
Error with comments app

### ISSUE THREAD

**Issue by izelli** [codysoyland/django-phased#2]
I got this error when I try to use phased with the comments forms to check if the user is authenticated:

`'functools.partial' object has no attribute '__module__'`

This is the code on the template:

{% load phased_tags %}
{% phased %}
{% load comments %}

{% if request.user.is_authenticated %}
`<a href="/exit/">Exit</a>`
{% render_comment_form for enq %}
{% else %}  
`<a href="/login/">login</a>`
{% endif %}

{% endphased %}

Is there something wrong with the code?

Thanks!

**Comment by izelli** [comment]
I made these changes on the utils.py to work, but I don't know if it affects something:

```
def find_components(parser):
    """
    Return a list of template tags library dotted paths to stash it away for
    later automagic loading during the second rendering.
    """
    modules = set()
    for func in itertools.chain(parser.tags.itervalues(), parser.filters.itervalues()):
        try:
            if func.__module__ not in forbidden_components:
                modules.add(func.__module__)
        except AttributeError:
            pass
    return list(modules)
```

**Comment by codysoyland** [comment]
This is definitely a valid issue, as curried view functions will not have the __module__ attribute. Your fix looks good but I just ran the tests and it seems they have been failing, but I'm not sure why. I'll look into that and get them passing before I push a fix for this.

**Comment by stefanw** [comment]
This issue just came up when trying out phased, however the proposed solution doesn't seem to be valid.

If you load template libraries that use shortcuts to register tags and filters (like `simple_tag`) their tags and filters will not have a `__module__` attribute, because they are wrapped in a method of a generated class that is wrapped in a function that is wrapped in a partial that is wrapped in a decorator. Finding the original `__module__` from that is close to impossible and definitely undesirable.

However, if you just skip over tags/filters, you will not be able to load the necessary tag libraries and their template tags/filters if used inside `phased` will fail.

Sadly there doesn't seem to be a way to get all loaded libraries out of the parser, because it only stores its tags/filters, not the name of the library they are coming from.

How could this be fixed? I can see some possible solutions:
1. Drop the functionality, making the loading of used libraries inside phased tags necessary once again.
2. Somehow separately extract `load` tags from the template, store them, reload them inside the second render phase.
   `parser.tokens` however contains only the remaining tokens, no `load` tags in there anymore.
3. Collect all blocks and filters inside the phased tag, detect if they are not inside the `builtin` libraries,
   find out in which of the libraries inside `django.template.base.libraries` global dict they are and store that library's name
   to reload in second render phase.

I'm currently working on a hack based on 3.

**Comment by jezdez** [comment]
This was fixed by removing the automatic pickling of used modules that was added in 7dd2abcdf741a91148327f0d696fa4bdfd227e13.
